# All the aruco gridboards in the map frame, and format (x, y, z, yaw) in meters and radians.
# Here, yaw is the angle between the face of the gridboard and the x axis of the map.
# The definitions for the gridboards (which marker ids and in what layout within the board) are in the aruco_gridboard config.
# board0: [0, 0, 1, 0]
# board00: [0, 0.8, 1, 0]
# board10: [2.9, -0.5, 1, -3.141592653]
board0: [0, 0, 1, 0]
board00: [0.89, -1.9, 1, -3.141592653]
board10: [0, -4.4, 1, 1.57]